AllCops:
  RunRailsCops: true
  Exclude:
    - db/schema.rb

ClassAndModuleChildren:
  Enabled: false

ClassLength:
  Enabled: false

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 150

Metrics/AbcSize:
  Max: 37

Metrics/ClassLength:
  Max: 150

Metrics/MethodLength:
  Max: 20

Style/IndentationWidth:
  Width: 2
